import re

def is_offense(message, bot_user):
    content = message.content.lower()

    if bot_user.name.lower() not in content and bot_user not in message.mentions:
        return False

    offensive_words = [
    "idiota",
    "imbecil",
    "burro",
    "burra",
    "bobo",
    "boba",
    "otário",
    "otária",
    "babaca",
    "trouxa",
    "tonto",
    "tonta",
    "estúpido",
    "estúpida",
    "ignorante",
    "inútil",
    "fracassado",
    "fracassada",
    "loser",
    "lerdo",
    "lerda",
    "tapado",
    "tapada",
    "lerdão",
    "lerdona",
    "mané",
    "moleque",
    "moleca",
    "palhaço",
    "palhaça",
    "idiotão",
    "idiotona",
    "imbecilão",
    "imbecilona",
    "burraço",
    "burraça",
    "cabeça-dura",
    "cabeça dura",
    "cabeçudo",
    "cabeçuda",
    "nojento",
    "nojenta",
    "ridículo",
    "ridícula",
    "patético",
    "patética",
    "insuportável",
    "chato",
    "chata",
    "irritante",
    "otário",
    "otaria",
    "babacão",
    "babacona",
    "cretino",
    "cretina",
    "canalha",
    "safado",
    "safada",
    "sem noção",
    "sem-noção",
    "sem vergonha",
    "sem-vergonha",
    "folgado",
    "folgada",
    "nojentão",
    "nojentona",
    "asqueroso",
    "asquerosa",
    "escroto",
    "escrota",
    "tosco",
    "tosca",
    "fracote",
    "fracotão",
    "fracotona",
    "incompetente",
    "desgraçado",
    "desgraçada",
    "maldito",
    "maldita",
    "cretinão",
    "cretinona",
    "imbecilzinho",
    "idiotinha",
    "bobalhão",
    "bobalhona",
    "palhação",
    "palhaçona",
    "trouxaço",
    "trouxona",
    "vacilão",
    "vacilona",
    "vacilante",
    "zé ruela",
    "ze ruela",
    "zé ninguém",
    "ze ninguem",
    "paspalho",
    "paspalha",
    "palerma",
    "energúmeno",
    "energumeno",
    "cretino",
    "babaca",
    "imbecil",
    "arrombado",
    "arrombada",
    "filha da puta",
    "filho da puta",
    "vai tomar no cu",
    "vai se fuder",
    "vai se ferrar",
    "vai se lascar"
]

    return any(re.search(rf"\b{re.escape(word)}\b", content) for word in offensive_words)